export const projectScope = [
  {
    id: 1,
    title: "Literature Survey",
    description: "",
    className: "lg:col-span-3 md:col-span-6 md:row-span-4",
    imgClassName: "w-full h-full",
    titleClassName: "justify-end",
    img: "/b1.svg",
    spareImg: "",
  },
  {
    id: 2,
    title: "Research Gap",
    description: "Here's what we provide",
    className: "lg:col-span-2 md:col-span-3 md:row-span-2",
    imgClassName: "",
    titleClassName: "justify-start",
    img: "",
    spareImg: "",
  },
  {
    id: 3,
    title: "Tech Stack",
    description: "",
    className: "lg:col-span-2 md:col-span-3 md:row-span-2",
    imgClassName: "",
    titleClassName: "justify-center",
    img: "",
    spareImg: "",
  },
  {
    id: 4,
    title: "Methodology",
    description: "",
    className: "lg:col-span-5 md:col-span-5 md:row-span-4",
    imgClassName: "",
    titleClassName: "justify-center",
    img: "",
    spareImg: "",
  },
];


export const timeline = [
  {
    id: 1,
    title: "Project Proposal",
    description: "",
    className: "lg:col-span-3",
    imgClassName: "",
    titleClassName: "justify-center",
    img: "",
    spareImg: "",
    altDescription:
      "CricBoost aims to secure funding and approval by presenting innovative tools designed for enhancing cricket training and performance. The project focuses on advanced solutions for analyzing bowling techniques, batting shot classification, ball tracking, and personalized training recommendations.",
  },
  {
    id: 2,
    title: "Progress Presentation I",
    description: "",
    className: "lg:col-span-2 justify-items-end",
    imgClassName: "",
    titleClassName: "justify-center",
    img: "",
    spareImg: "",
    altDescription:
      "A Progress Presentation details the completed work, covering 50% of the project milestones achieved so far.",
  },
  {
    id: 3,
    title: "Research Paper",
    description: "",
    className: "lg:col-span-2 justify-items-end",
    imgClassName: "",
    titleClassName: "justify-center",
    img: "",
    spareImg: "",
    altDescription:
      "A Research Paper details the findings and insights gathered from our study.",
  },
  {
    id: 4,
    title: "Progress Presentation II",
    description: "",
    className: "lg:col-span-3 justify-items-end",
    imgClassName: "",
    titleClassName: "justify-center",
    img: "",
    spareImg: "",
    altDescription:
      "Progress Presentation II outlines the work completed, demonstrating 90% project completion and key milestones achieved.",
  },
  {
    id: 5,
    title: "App Website Designing",
    description: "",
    className: "lg:col-span-3 justify-items-end",
    imgClassName: "",
    titleClassName: "justify-center",
    img: "",
    spareImg: "",
    altDescription:
      "App Website Designing focuses on creating an intuitive and engaging online presence for our app, enhancing user experience and accessibility.",
  },
  {
    id: 6,
    title: "Research Logbook",
    description: "",
    className: "lg:col-span-2 justify-items-end",
    imgClassName: "",
    titleClassName: "justify-center",
    img: "",
    spareImg: "",
    altDescription:
      "A Research Logbook documents the ongoing research activities, methodologies, and findings throughout the project.",
  },
  {
    id: 7,
    title: "Final Report",
    description: "",
    className: "lg:col-span-2 justify-items-end",
    imgClassName: "",
    titleClassName: "justify-center",
    img: "",
    spareImg: "",
    altDescription:
      "The Final Report summarizes the entire project, detailing objectives, methodologies, results, and conclusions.",
  },
  {
    id: 8,
    title: "Final Presentation & Viva",
    description: "",
    className: "lg:col-span-3 justify-items-end",
    imgClassName: "",
    titleClassName: "justify-center",
    img: "",
    spareImg: "",
    altDescription:
      "The Final Presentation & Viva highlights the project outcomes, key achievements, and includes a Q&A session to defend and discuss the work.",
  },
];

export const docs = [
  {
    id: 1,
    title: "Project Proposal",
    className: "lg:col-span-3",
    titleClassName: "justify-center",
    link:"https://docs.google.com/presentation/d/1lU709bJjEpF_mLFgoHeuT49eBgo7up9c/edit?usp=drive_link&ouid=100167178454560611950&rtpof=true&sd=true",
    altDescription:"Presentation" },
    {
      id: 2,
      title: "Project Proposal [Individual Reports]",
      className: "lg:col-span-3",
      titleClassName: "justify-center",
      link:"https://drive.google.com/drive/folders/1liCmlR7iNjYzdfQMn_qInvsymr7fj8Yq?usp=drive_link",
      altDescription:"Document" },
    {
      id: 3,
      title: "Status Documents 1",
      className: "lg:col-span-2 justify-items-end",
      titleClassName: "justify-center",
      link:"https://drive.google.com/drive/folders/1XMsAl-uhoXHyvS29wgBxV3FJeF7pFmyP?usp=drive_link" ,
      altDescription:"Document" },
    
  {
    id: 4,
    title: "Progress Presentation I",
    className: "lg:col-span-2 justify-items-end",
    titleClassName: "justify-center",
    link:"https://drive.google.com/drive/folders/1P2g8O8fRggiaBZYFu9mONt_tK_EmbfWh?usp=sharing" ,
    altDescription:"Presentation" },
  {
    id: 5,
    title: "Research Paper",
    className: "lg:col-span-2 justify-items-end",
    titleClassName: "justify-center",
    link:"https://drive.google.com/drive/folders/1Mkf2us4WCP1n-cD1A47oxEHv_8zSzxIF?usp=sharing" ,
    altDescription:"Document"  },
  {
    id: 6,
    title: "Progress Presentation II",
    className: "lg:col-span-3 justify-items-end",
    titleClassName: "justify-center",
    link:"" ,
    altDescription:"Presentation" },
  {
    id: 7,
    title: "Status Documents 2",
    className: "lg:col-span-3 justify-items-end",
    titleClassName: "justify-center",
    link:"https://drive.google.com/drive/folders/1D5T2jhKoFGChhnSISxxm_Qr4O4-HFaaH?usp=sharing" ,
    altDescription:"Document", },
  {
    id: 8,
    title: "Research Logbook",
    className: "lg:col-span-2 justify-items-end",
    titleClassName: "justify-center",
    link:"https://drive.google.com/drive/folders/1tNWpIomPt4F0UxhJgL3iSPaSJxd_g7ca?usp=sharing",
    altDescription:"Document" },
  {
    id: 9,
    title: "Final Report",
    className: "lg:col-span-2 justify-items-end",
    titleClassName: "justify-center",
    link:"https://drive.google.com/drive/folders/14pkTq17f93_AmEuWGVLrcIck9MlB0_Px?usp=sharing",
    altDescription:"Document"  },
  {
    id: 10,
    title: "Final Presentation",
    className: "lg:col-span-3 justify-items-end",
    titleClassName: "justify-center",
    link:"https://drive.google.com/drive/folders/1BMsIMna78g-fkdLbE9dCw7vL3wjoxxLp?usp=sharing" ,
    altDescription:"Presentation" },
];


export const teams = [
  {
    id: 1,
    title: "",
    description: "",
    className: "lg:col-span-5",
    imgClassName: "",
    titleClassName: "justify-center",
    img: "",
    spareImg: "",
  },
];
